# Create a new user
POST http://localhost:4000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "user12@notfound.local",
  "dateBirth": "2004-09-21",
  "name": "Keks",
  "password": "123456",
  "role": "Тренер",
  "level": "новичок",
  "sex": "мужской",
  "location": "Спортивная",
  "description": "описание 1",
  "trainingType": ["аэробика", "бег"],
  "merits": "Заслуга 11111",
  "personalTrainings": false,
  "certificates": "example.pdf"
}

###

# Login user by email and password
POST http://localhost:4000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "Isac93@gmail.com",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:4000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTMxNjhiNTJiYjZmYmViYjJmMDYzNTMiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0J_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Iktla3MiLCJ0b2tlbklkIjoiOGYzM2RkNTAtNmNlZS00MGYyLTkwYTUtM2ZiZmQ4MGU5ZGRjIiwiaWF0IjoxNjk3OTk2MjQwLCJleHAiOjE2OTg2MDEwNDB9.CVrU4bwUcdwjdu3vsvM3sAOqEwzu360dMeTec1zWSqc

###

# Delete user's refresh tockens by userID
DELETE http://localhost:4000/api/users/6535647eeefd7a37a4cb3bda HTTP/1.1

###

# Update user
PATCH http://localhost:4000/api/users/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTNkNGNlMWRiODE4NmZlYzEwMmQ4OGMiLCJlbWFpbCI6InVzZXIxMkBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiLQotGA0LXQvdC10YAiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTY5ODUxNjIwNywiZXhwIjoxNjk4NTE3MTA3fQ.6-HR0ZjHwEsGli2nP0HRXWDr6w_yd0u17KRm4k1-CC0

{
  "description": "Описание 1.3"
}

###

# Get user by id
GET http://localhost:4000/api/users/6537ed54daf7a45404e304c1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YmEiLCJlbWFpbCI6IklnbmFjaW8uRGFjaDRAZ21haWwuY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJJcmlzIEJyYWR0a2UgViIsImlhdCI6MTY5ODc1Mjc5MSwiZXhwIjoxNjk4NzUzNjkxfQ.ZxEwK-VD-1G8CM2TkFwi87L7jGN8KALcFMSDiKfB0sI

###

# Get all users
GET http://localhost:4000/api/users?limit=2&page=3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YjgiLCJlbWFpbCI6IktheWxpbl9IZXJtYW5uNDlAeWFob28uY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJMZXJveSBTbWl0aCIsImlhdCI6MTY5ODUxNzcyMSwiZXhwIjoxNjk4NTE4NjIxfQ.0YYQ1GpIwf5hsgaJm0o7WWUBZeKU0yEoqhf35gUv-W8

###

# Get users friends
POST http://localhost:4000/api/users/friends?limit=1&page=2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YjgiLCJlbWFpbCI6IktheWxpbl9IZXJtYW5uNDlAeWFob28uY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJMZXJveSBTbWl0aCIsImlhdCI6MTY5ODUxNzcyMSwiZXhwIjoxNjk4NTE4NjIxfQ.0YYQ1GpIwf5hsgaJm0o7WWUBZeKU0yEoqhf35gUv-W8

###

# Add friend
PATCH http://localhost:4000/api/users/6537ed54daf7a45404e304be HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YjgiLCJlbWFpbCI6IktheWxpbl9IZXJtYW5uNDlAeWFob28uY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJMZXJveSBTbWl0aCIsImlhdCI6MTY5ODg1OTQyNCwiZXhwIjoxNjk4ODYwMzI0fQ.xi4jggJpiGNM3G0tdSH4dI5WGNs182Fp0n3usPDAUC4

###

# Delete friend
DELETE http://localhost:4000/api/users/6537ed54daf7a45404e304bd HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YmEiLCJlbWFpbCI6IklnbmFjaW8uRGFjaDRAZ21haWwuY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJJcmlzIEJyYWR0a2UgViIsImlhdCI6MTY5ODc1Mjc5MSwiZXhwIjoxNjk4NzUzNjkxfQ.ZxEwK-VD-1G8CM2TkFwi87L7jGN8KALcFMSDiKfB0sI

###

# Add subscription
PATCH http://localhost:4000/api/users/subscriptions/6537ed54daf7a45404e304be HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YmEiLCJlbWFpbCI6IklnbmFjaW8uRGFjaDRAZ21haWwuY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJJcmlzIEJyYWR0a2UgViIsImlhdCI6MTY5ODc1Mjc5MSwiZXhwIjoxNjk4NzUzNjkxfQ.ZxEwK-VD-1G8CM2TkFwi87L7jGN8KALcFMSDiKfB0sI

###

# Delete subscription
DELETE http://localhost:4000/api/users/subscriptions/6537ed54daf7a45404e304c1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YmEiLCJlbWFpbCI6IklnbmFjaW8uRGFjaDRAZ21haWwuY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJJcmlzIEJyYWR0a2UgViIsImlhdCI6MTY5ODc1Mjc5MSwiZXhwIjoxNjk4NzUzNjkxfQ.ZxEwK-VD-1G8CM2TkFwi87L7jGN8KALcFMSDiKfB0sI

###

####################################################

# Create a new training
POST http://localhost:4000/api/training HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YzEiLCJlbWFpbCI6IkFsaWNlX0tyZWlnZXJAZ21haWwuY29tIiwicm9sZSI6ItCi0YDQtdC90LXRgCIsIm5hbWUiOiJEci4gQW5kcmUgTXVycmF5IiwiaWF0IjoxNjk4ODUwMzA5LCJleHAiOjE2OTg4NTEyMDl9.q42zKxt5bkRlzoO342UuIEMim2oZ6gRFj2k2sRECjWU

{
  "title": "Тренировка 69",
  "backgroundImage": "image2.jpg",
  "level": "любитель",
  "trainingType": "бокс",
  "trainingTime": "50-80 мин",
  "price": 400,
  "caloriesCount": 1000,
  "description": "описание 4",
  "sex": "для мужчин",
  "video": "example.avi",
  "special": true
}

###

# Get my tainings
GET http://localhost:4000/api/training/trainer HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTNkMjI3YTQ5Y2MwZDc4MzY2ZjY3MzgiLCJlbWFpbCI6InVzZXIxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiLQotGA0LXQvdC10YAiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTY5ODUxOTAyNywiZXhwIjoxNjk4NTE5OTI3fQ.0TjTl5ahxAZYncFl04_sfgwceICkJ1JOnx0L7iZ2LBI

###

# Get training by id
GET http://localhost:4000/api/training/10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTNkNGNlMWRiODE4NmZlYzEwMmQ4OGMiLCJlbWFpbCI6InVzZXIxMkBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiLQotGA0LXQvdC10YAiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTY5ODUyMDE4MCwiZXhwIjoxNjk4NTIxMDgwfQ.xkt-wOIYUVXwaKfugSBasoklF3XRLI_ZdEvf3cbRqGw

###

# Update training by id
PATCH http://localhost:4000/api/training/10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTNkNGNlMWRiODE4NmZlYzEwMmQ4OGMiLCJlbWFpbCI6InVzZXIxMkBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiLQotGA0LXQvdC10YAiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTY5ODUyMTQ2MSwiZXhwIjoxNjk4NTIyMzYxfQ.tNp5z1BE0KCsbZYLxku2VmExHk7bmEfhsHBIH5otV5U

{
  "title": "Тренировка 4.1",
  "price": 110
}

###

# Get all tainings (catalog)
GET http://localhost:4000/api/training?limit=4&page=2&minPrice=100&maxPrice=300 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YjgiLCJlbWFpbCI6IktheWxpbl9IZXJtYW5uNDlAeWFob28uY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJMZXJveSBTbWl0aCIsImlhdCI6MTY5ODU3ODUxMiwiZXhwIjoxNjk4NTc5NDEyfQ.5BTjxpelv9JzRmp0xrC3qBZSOICnb3YH1XL_VuUu11c

###



#####################################################

# Create a new order
POST http://localhost:4000/api/order HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YjgiLCJlbWFpbCI6IktheWxpbl9IZXJtYW5uNDlAeWFob28uY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJMZXJveSBTbWl0aCIsImlhdCI6MTY5ODU3NDI5MSwiZXhwIjoxNjk4NTc1MTkxfQ.yTAAFP1ZQYLV69aM6okBSfQmedCJSxj3HL9Jm-9jCbk

{
  "type": "абонемент",
  "trainingId": 11,
  "count": 2,
  "trainingTime": "50-80 мин",
  "paymentMethod": "mir",
  "description": "описание 112"
}

###

# Get orders by trainerId
GET http://localhost:4000/api/order/trainer?limit=2&sortDirection=desc HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTNkNGNlMWRiODE4NmZlYzEwMmQ4OGMiLCJlbWFpbCI6InVzZXIxMkBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiLQotGA0LXQvdC10YAiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTY5ODU3NTIzOCwiZXhwIjoxNjk4NTc2MTM4fQ.i63bYtUO3u1ucezmEuiBfCSIm1zdTe5dcy3N3ubkqWc

###

# Get orders by userId
GET http://localhost:4000/api/order/user?limit=2&sortDirection=desc&active=true HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YjgiLCJlbWFpbCI6IktheWxpbl9IZXJtYW5uNDlAeWFob28uY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJMZXJveSBTbWl0aCIsImlhdCI6MTY5ODc1ODkxNiwiZXhwIjoxNjk4NzU5ODE2fQ.D6tdfva_g0stgoOITvB2W4cyrdfdNkNIQhMkLuasorY

###

# Update order activ by id
PATCH http://localhost:4000/api/order/16 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YjgiLCJlbWFpbCI6IktheWxpbl9IZXJtYW5uNDlAeWFob28uY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJMZXJveSBTbWl0aCIsImlhdCI6MTY5ODc1ODkxNiwiZXhwIjoxNjk4NzU5ODE2fQ.D6tdfva_g0stgoOITvB2W4cyrdfdNkNIQhMkLuasorY

{
  "active": true
}

###


##########################################

# Send Email
POST http://localhost:4000/api/users/email/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YmEiLCJlbWFpbCI6IklnbmFjaW8uRGFjaDRAZ21haWwuY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJJcmlzIEJyYWR0a2UgViIsImlhdCI6MTY5ODc1MzY5MSwiZXhwIjoxNjk4NzU0NTkxfQ.Zvv0SX04oIHDbgAJHymDqJ-M8oXlGcpHrn-WFVZLe9M

###


##########################################

# Get alerts by userId
POST http://localhost:4000/api/users/alerts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YmUiLCJlbWFpbCI6IklzYWM5M0BnbWFpbC5jb20iLCJyb2xlIjoi0KLRgNC10L3QtdGAIiwibmFtZSI6IlNvbmphIENvbnNpZGluZSIsImlhdCI6MTY5ODg1OTUwMywiZXhwIjoxNjk4ODYwNDAzfQ.yZEAxzyUjtecQ2KGssOjT22yo9skijr0Sz0kVbTQFEg

###

# Delete alert by id
DELETE http://localhost:4000/api/users/alerts/654271f03f7e86c410103a3d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YmUiLCJlbWFpbCI6IklzYWM5M0BnbWFpbC5jb20iLCJyb2xlIjoi0KLRgNC10L3QtdGAIiwibmFtZSI6IlNvbmphIENvbnNpZGluZSIsImlhdCI6MTY5ODg1OTUwMywiZXhwIjoxNjk4ODYwNDAzfQ.yZEAxzyUjtecQ2KGssOjT22yo9skijr0Sz0kVbTQFEg

###
