# Get alerts by user ID
GET http://localhost:3335/api/alert/6537ed54daf7a45404e304bd HTTP/1.1

###


# Delete alert by ID
DELETE http://localhost:3335/api/alert/654271a03f7e86c410103a35 HTTP/1.1

###
