# Create a new order
POST http://localhost:3000/api/orders HTTP/1.1
Content-Type: application/json

{
  "type": "абонемент",
  "trainingId": 3,
  "count": 3,
  "trainingTime": "50-80 мин",
  "paymentMethod": "visa",
  "description": "описание 2",
  "userId": "3"
}

###

# Get orders by userId
GET http://localhost:3000/api/orders/user/6537ed54daf7a45404e304b8?limit=3&page=2 HTTP/1.1

###

# Get orders by trainerId
GET http://localhost:3000/api/orders/trainer/1?sortField=idCount&sortDirection=asc&limit=1&page=2 HTTP/1.1

###

# Update order activ by id
PATCH http://localhost:3000/api/orders/17 HTTP/1.1
Content-Type: application/json

{
  "active": false
}

###
