version: '3.9'
services:
  fitFriends.users.mongodb:
    image: mongo:4.2
    container_name: fitFriends.users.mongodb
    restart: always
    env_file:
      - .fit-friends.users.mongodb.env
    volumes:
      - fitFriends.users.volume:/data/db
    networks:
      - fitFriends.users.network

  fitFriends.users.rabbitmq:
    image: rabbitmq:3.11-management
    container_name: fitFriends.users.rabbitmq
    restart: always
    env_file:
      - '.fit-friends.users.env'
    ports:
      - '1098:15672'
      - '5682:5672'
    networks:
      - fitFriends.users.network

  fitFriends.users.mongo.ui:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    container_name: fitFriends.users.mongo.ui
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@fitFriends.users.mongodb:27017/
    networks:
      - fitFriends.users.network

  fitFriends.users:
    container_name: fitFriends.users
    depends_on:
      - fitFriends.users.mongodb
    restart: always
    image: fit-friends.users:latest
    env_file:
      - .fit-friends.users.env
    environment:
      - NODE_ENV=production
    ports:
      - 3333:3333
    networks:
      - fitFriends.users.network

networks:
  fitFriends.users.network:
    driver: bridge

volumes:
  fitFriends.users.volume:
