# Get all users
GET http://localhost:3333/api/user?limit=2&page=3 HTTP/1.1
###

# add Friends
PATCH http://localhost:3333/api/user/653383f1780101af165b7826 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTMxNmQ0ZDQ2YTk3Yzc1YmI4ZjkyMDAiLCJlbWFpbCI6InVzZXIzQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItCi0YDQtdC90LXRgCIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjk3OTY5ODQ4LCJleHAiOjE2OTc5NzA3NDh9.jA0ZKdrWk6AfUs9a3hgBHF4fyMgGLrUEflKqDDdnijA

###
