# Get all users
GET http://localhost:3333/api/user?readyToTraining=true HTTP/1.1
###

# Add friend
PATCH http://localhost:3333/api/user/6537ed54daf7a45404e304bc HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YjgiLCJlbWFpbCI6IktheWxpbl9IZXJtYW5uNDlAeWFob28uY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJMZXJveSBTbWl0aCIsImlhdCI6MTY5ODY5MDU3NSwiZXhwIjoxNjk4NjkxNDc1fQ.rIylCB860vzHlvelT2v5OkxbNy0rAeoLmsfCgIvXXd8

###

# Delete friend
DELETE http://localhost:3333/api/user/653383f1780101af165b7826 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTMxNmQ0ZDQ2YTk3Yzc1YmI4ZjkyMDAiLCJlbWFpbCI6InVzZXIzQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItCi0YDQtdC90LXRgCIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjk3OTkyNTg0LCJleHAiOjE2OTc5OTM0ODR9.LkpVoclD7fsteXXqUfKlrNxu81z2USBdVEaJYVqtbMU

###

# Get users friends
GET http://localhost:3333/api/user/friends?limit=1&page=2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTMxNjhiNTJiYjZmYmViYjJmMDYzNTMiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0J_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Iktla3MiLCJpYXQiOjE2OTgwNzczMTUsImV4cCI6MTY5ODA3ODIxNX0.Jnwa9NlVPXYY6NCMeWPZMKy0cNqf7cOEqk12PI_kVvY

###

# Add subscription
PATCH http://localhost:3333/api/user/subscription/6537ed54daf7a45404e304bc HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YjgiLCJlbWFpbCI6IktheWxpbl9IZXJtYW5uNDlAeWFob28uY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJMZXJveSBTbWl0aCIsImlhdCI6MTY5ODY5MDU3NSwiZXhwIjoxNjk4NjkxNDc1fQ.rIylCB860vzHlvelT2v5OkxbNy0rAeoLmsfCgIvXXd8
###

# Delete subscription
DELETE http://localhost:3333/api/user/subscription/6537ed54daf7a45404e304bb HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YjgiLCJlbWFpbCI6IktheWxpbl9IZXJtYW5uNDlAeWFob28uY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJMZXJveSBTbWl0aCIsImlhdCI6MTY5ODY4Njc5NiwiZXhwIjoxNjk4Njg3Njk2fQ.oF2MNbHSbY6OcruFMutLT2_nVhj1dU7GPERfa7TQUwI

###

# Get user subscriptions
GET http://localhost:3333/api/user/subscriptions HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTUwZmFjODhjYjJiYjAwYTkyOGYwNGEiLCJlbWFpbCI6Imtla3NAaHRtbGFjYWRlbXkucnUiLCJyb2xlIjoi0J_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Iktla3MgS2Vrc2lrIiwiaWF0IjoxNzAzOTUwNDc3LCJleHAiOjE3MDM5NTEzNzd9.O8NphZQgWQvyeBvK6VIIEE5uXkG74u4Te9BmORGdT0o

###

# Get trainer in subscriptions
GET http://localhost:3333/api/user/subscription/6537ed54daf7a45404e304c1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTM3ZWQ1NGRhZjdhNDU0MDRlMzA0YmEiLCJlbWFpbCI6IklnbmFjaW8uRGFjaDRAZ21haWwuY29tIiwicm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsIm5hbWUiOiJJcmlzIEJyYWR0a2UgViIsImlhdCI6MTY5ODc1MzIwMSwiZXhwIjoxNjk4NzU0MTAxfQ.F1iZ9uLCJDrH8Tcb1XP5TLH29pXjD7rsiDob09GuszE

###
